import type { Metadata } from "next";
import localFont from "next/font/local"; 
import "./globals.css";





const normalText = localFont({

  src: "../public/fonts/normal-text.woff2",
  variable: "--font-normal-text", 
  display: "swap",
});

const headingBold = localFont({

  src: "../public/fonts/heading-bold.woff2",
  variable: "--font-heading-bold", 
  display: "swap",
});

const headingXBold = localFont({

  src: "../public/fonts/heading-xbold.woff2",
  variable: "--font-heading-xbold",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
        className={`${normalText.variable} ${headingBold.variable} ${headingXBold.variable} antialiased`}
      >
        
        {children}
   
      </body>
    </html>
  );
}